apiVersion: v1
kind: Secret
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_USER: YWRtaW4=
